name: Deploy to heroku

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  run_if:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dispersed-api"
          heroku_email: "bryce@brycekennedy.net"
